### ISSUE TITLE
Under construction

### ISSUE THREAD

**Issue by oldgandalf** [3design/GlobalBrainConsortium.org#10]
Hi Derek
Please add a new event to the Events List, named “Global Mental Health” below "Long Covid".

Please mark both of them:

Long Covid and Global Mental Health as under construction

**Comment by christinerogers** [comment]
@oldgandalf Should these be in the EVents list or the Projects List?

**Comment by oldgandalf** [comment]
Projects List, sorry

**Comment by christinerogers** [comment]
looks great! closing
