### ISSUE TITLE
Figure replace

### ISSUE THREAD

**Issue by oldgandalf** [3design/GlobalBrainConsortium.org#12]
Derek

I uploaded an updated version of the figure Processing Pipeline to the GlobalEEGNorms website, with spelling corrections. Please substitute the old one you have.

The figure in the banner in the webpage is not resizing, so only a few portions are shown on the webpage.

The carrousel is too big. Nothing can be seen apart from the banner and carrousel. To start looking at some text one needs to scroll down. It would be preferable to remove the banner then.

I liked the two images with the text Overview and Goals as Christine had before. Is it possible to put them back?

Also, we are wasting too much space on the screen. Maybe not for this week, but I would like to see how we can better use the space to show more information at the first glance.

The carousel also is quite big. I think reducing it by 20% would benefit to have more information on the screen.

**Comment by 3design** [comment]
I have done the following:
- replaced the image for the banner
- reduced the banner size globally by 100px
- commented out the map and norm image in the carousel
- returned the above images to the text boxes

The other issues require quite a bit of re-coding of the entire website. I recommend we speak about this at a later date and break this into actionable items.

**Comment by christinerogers** [comment]
Ok great!  We are closing this issue for now. 
 @oldgandalf (and/or @3design) Please open a **new issue** to highlight what you would like to be done/discussed next in this page with images.
