### ISSUE TITLE
Small fixing in the EEGNorms webpage

### ISSUE THREAD

**Issue by oldgandalf** [3design/GlobalBrainConsortium.org#15]
Hi Derek

very nice job with the EEGNorms page. Just 2 things:

1) Can you please reduce the high of the carousel so more information is shown on the page?

2) Please add the names of the countries in the institutes,at the end of the list of participants

University of Electronic Science and Technology of China (UESTC), China
Montreal Neurological Institute, Canada
Cuban Neuroscience Center (CNeuro), Cuba
Federal Research Center for Information and Computational Technologies, Russia
Institute of Cytology and Genetics Siberian Branch, Russia
Universidad de Antioquia, Colombia
Universiti Sains Malaysia, Malaysia
University of Zurich, Switzerland
University Hospital of Clinical Psychiatry, Bern, Switzerland
Brain Research Laboratories, New York University, USA
Mass General Hospital for Children, Boston, USA
Centro Internacional de Restauracion Neurológica (CIREN), Cuba
CITED, Cuba
Max Planck Institute for Human Cognitive and Brain Sciences, Germany

**Comment by christinerogers** [comment]
ok closing :)
