### ISSUE TITLE
Banner image for the Barbados Study

### ISSUE THREAD

**Issue by oldgandalf** [3design/GlobalBrainConsortium.org#23]
Hi Derek
I put a new image on the Barbados Web page, Banner images, to see if it looks better as the banner image of the Barbados webpage.

https://lstneuro.sharepoint.com/sites/GlobalBrainConsortiumGBC/Shared%20Documents/IOP-Electrophysiology%20as%20a%20Tool%20for%20Global%20Health/Projects/BarbardosNutritionStudy/BannerImages/SampleAgeDistribution.jpg

**Comment by 3design** [comment]
I have put the supplied image in the spot though I don't think it fits too well as the main colour of the image is white, and the page title label is also white. The banner image was originally made for colourful full screen images as a background only. Is there a research institution in barbados we can use for the background?

**Comment by christinerogers** [comment]
(page link here for preview/reference: https://3design.github.io/GlobalBrainConsortium.org/project-barbados.html )

**Comment by christinerogers** [comment]
@oldgandalf could you please close issue #16 if it is no longer something Derek should act on?

**Comment by oldgandalf** [comment]
I will close the issue but I made a mistake. The new banner image is not for the Barbados study, but for the normative study. Sorry.
Anyway, I don´t see any change in the Barbados webpage. So, closing here and opening a new one.
