### ISSUE TITLE
Update an image in the Global EEG Norms project

### ISSUE THREAD

**Issue by oldgandalf** [3design/GlobalBrainConsortium.org#37]
Derek
Please, can you update one image in the Global EEG Norms?

Just take the image "Global Normative Surface.JPG" in Teams and reload to the GBC webpage. I made a little change to this image.

https://lstneuro.sharepoint.com/sites/GlobalBrainConsortiumGBC/Shared%20Documents/IOP-Electrophysiology%20as%20a%20Tool%20for%20Global%20Health/Projects/GlobalEEGNorms/BannerImages/Global%20Normative%20Surface.jpg

Thanks

**Comment by christinerogers** [comment]
looks great! closing this 👍
