### ISSUE TITLE
Projects page: add Barbados thumbnail

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#39]
currently default gbc thumbnail is used for the Barbados project on the [project-lists.html page](https://3design.github.io/GlobalBrainConsortium.org/projects.html). 

Best image to substitute? any thoughts @oldgandalf?

**Comment by christinerogers** [comment]
Hi @oldgandalf that image is not ideal for a thumbnail, it has a great deal of information and will not be easy to look at when very small.  
Could you suggest us a simpler image?

**Comment by oldgandalf** [comment]
Hi @christinerogers see if this image fits as the Barbados thumbnail

https://lstneuro.sharepoint.com/sites/GlobalBrainConsortiumGBC/Shared%20Documents/IOP-Electrophysiology%20as%20a%20Tool%20for%20Global%20Health/Projects/BarbardosNutritionStudy/BannerImages/thumbnail.jpg

you can incorporate the other one into the carousel

**Comment by christinerogers** [comment]
Hi @oldgandalf  - the brains still look odd when the image is tiny, but this veresion helps, thank you.  
(if you can take out the brains, could you? and paste new link here) 

@3design Can you please add the image in Bosch's latest comment as the Barbados thumbnail on (only) the projects.html page? 
(There currently a generic GBC image for this thumbnail)

Thank you both

**Comment by christinerogers** [comment]
Looks much improved.  I send Bosch the link and he is good with it.  
Thank you both.
