### ISSUE TITLE
Contact form in GBC site - Googleform owner/edit?

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#48]
For the GoogleForm embedded in the GBC Contact Page : https://docs.google.com/forms/d/e/1FAIpQLSeKTq37geZBhpgo8r6PSBeHWcHuFhOd_VWYekJnPNiVBRdbKw/viewform

@3design  If you can, please: 

- [x] Give Edit privilege to christine.rogers@mcin.ca for that form.  (i just want to see responses for now) 

 if you can't... Could you help us find out who made/owns that form? 

thanks very much 
C

**Comment by 3design** [comment]
@christinerogers shared the folder with you on google drive

**Comment by christinerogers** [comment]
thanks! i see the invitation.
