### ISSUE TITLE
Smooth/fix text in Barbados page

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#49]
**Updated text for Overview column  :** 

This multinational project aims to study the long-term effects of early malnutrition in the life of people who suffered it. 

The BNS is a 45-years longitudinal study which has compiled follow up information for a group of Barbadian children who suffered Protein energy malnutrition (PEM) during their first year of life. 45 years later, this population shows signs of early aging and cognitive decline, as well as other psychological and physiological sequalae. Novel statistical mediation methodology is being used to observe metabolic, nutritional, economical, psychological, brain electrical activity, integrated across all data and information to describe these alterations in normal development. 

**Updated text for Goals column:** 

This multi-national collaboration invites other researchers to contribute their own methodologies and multimodal analyses to better describe and understand these datasets. At the same time, this research initiative confers with investigators collecting data from other populations to better understand the foundations of developmental factors. 
              </p><p>
Given the global prevalence of malnutrition in all parts of the world, the outcome of this study aims to produce evidence about the persistent negative effects of malnutrition in early life, applicable to supporting intervention and policy initiatives across international organizations and governments working to address these challenges. 
              </p>

**Comment by christinerogers** [comment]
@oldgandalf - Could you review and let me know if it is ok? I have fixed some of the English and smoothed over some of the text and would like to put this online Thursday.

**Comment by oldgandalf** [comment]
@christinerogers I find it perfect. Thanks

**Comment by christinerogers** [comment]
@3design  ready for you -  we'll go live today when this and the other "next priority" change are all ready.

**Comment by christinerogers** [comment]
note to self; too many "global" in second column. 

fine for now - closing
