### ISSUE TITLE
News page: IOP conference (BOSCH to complete)

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#5]
Bosch @oldgandalf to complete for Derek:

- [ ] Which page is it on? 
- [ ] What part / element of the page? 
- [ ] Specific action to take
- [ ] Source file/information : Link to image file or specific text to paste in
- [ ] Any wording that need to be added.

ideas : 
? documents : exactly which PDF (teams link here) for

? Need a better image for the IOP conference.

-? any improvements to the text you seen on the page?

**Comment by oldgandalf** [comment]
Hi Christine. I don't understand this issue. I already wrote very detailed all the things related to the IOP conference.

**Comment by christinerogers** [comment]
Great, I will close this issue and just migrate your notes from https://github.com/christinerogers/GlobalBrainConsortium/issues/11 to a new issue in this repo - thanks for pointing me there.
