### ISSUE TITLE
projects.html change all the project names.  add description blurbs.  

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#60]
in projects.html : 

Use the [Teams agenda](https://lstneuro.sharepoint.com/:w:/r/sites/GlobalBrainConsortiumGBC-PrivateOrganization/Shared%20Documents/PrivateOrganization/GBC%20Annual%20Meeting%202021/GBC%202021%20Agenda/GBC%20Nov2021%20Agenda%20Annual%20Meeting%203%20Nov%202021.docx?d=w730c6a3b274841388160aaab857a5af7&csf=1&web=1&e=LOn9Li) to : 
- [x] update All project names 
- [x] put the project description blurb under each Thumbnail image.

**Comment by 3design** [comment]
@christinerogers do the description blurbs replace the current descriptions?

**Comment by christinerogers** [comment]
👍
