### ISSUE TITLE
Selecteed instead of Select

### ISSUE THREAD

**Issue by oldgandalf** [3design/GlobalBrainConsortium.org#68]
@3design & @christinerogers @

- in all projects, instead of Select it should be Selected Publications
- in the Covid project, remove the list of participants. The Cuban Neuroscience Center should go first, UESTC should not be listed in front
-

**Comment by christinerogers** [comment]
this can be done Friday if derek has time ?

**Comment by christinerogers** [comment]
@oldgandalf please review these changes  asap on https://3design.github.io/GlobalBrainConsortium.org/
and let derek know *in a new issue* if you want further changes. 

but i  think this is good to go so i am closing 👍
