### ISSUE TITLE
NovMtg : add OneNote / OneDrive info

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#70]
on the "Project Documents" panel at left 

- [x] change button: "coming soon" to "read more"
- [x] change the link on button: 

see link below

**Comment by 3design** [comment]
@christinerogers I am unclear on which html page this is referring to. Could you please advise?

**Comment by christinerogers** [comment]
https://lstneuro.sharepoint.com/:f:/s/GlobalBrainConsortiumGBC/EkvCs_BEwqtEpvfkVWtc4NsBjmIiUcx3rslOO-dFnUM8Xg?e=ngG2L5

this is the link. 🤞

**Comment by christinerogers** [comment]
link works.   i did a followup tweak to button wording in #72
