### ISSUE TITLE
Include a News

### ISSUE THREAD

**Issue by oldgandalf** [3design/GlobalBrainConsortium.org#77]
2nd. International Neurodevelopment Congress.
Organized by the Neurodevelopment Research Unit, Institute for Neurobiology, UNAM.
Led by Dr. Thalia Harmony.
September 8-10, 2022
Virtual
https://www.neurodevelopmentcongress.com/
https://www.facebook.com/congresoneurodesarrollo/

The image for the announcement can be taken from the webpage

**Comment by oldgandalf** [comment]
I have uploaded all necessary information to create the News here: 
https://lstneuro.sharepoint.com/:f:/s/GlobalBrainConsortiumGBC/EmzfehPNyXJHt7o0xLqHNx0B0aEKfk815gPHU0fzFAJClw?e=lncEvT

**Comment by christinerogers** [comment]
Hi Bosch could you kindly include all / brief details for the briefly in this issue? Then I can review it and green-light it

**Comment by oldgandalf** [comment]
Hi Christine. I don't understand, I put all the details in Teams. What do you need?

**Comment by oldgandalf** [comment]
I put some more images. Use the ones best fit you, Derek.

**Comment by christinerogers** [comment]
@3design do you have all the information here you need?  what's missing?  thanks

**Comment by 3design** [comment]
https://3design.github.io/GlobalBrainConsortium.org/news.html

**Comment by christinerogers** [comment]
👍 good enough and merci derek
