### ISSUE TITLE
New News for the GBC webpage

### ISSUE THREAD

**Issue by oldgandalf** [3design/GlobalBrainConsortium.org#78]
32nd International Congress of Clinical Neurophysiology
Organized by The International Federation of Clinical Neurophysiology along with the Swiss Society of Clinical Neurophysiology
September 4–8, 2022 in Geneva, Switzerland

https://www.braincouncil.eu/event/32nd-international-congress-of-clinical-neurophysiology/
https://ifcn.site-ym.com/mpage/ICCN2022

Two symposia organized by the GBC-OHBM-IFCN

**Quantitative Neuroimaging of Public Health problems: Examples from Latin America**
Chair: Jorge Bosch-Bayard (Montreal Neurological Institute)

**EEG in the clouds** 
Chair: Pedro A. Valdes Sosa

https://ifcn.site-ym.com/mpage/ProgrammeOverview

And an advertisement spot, where members are invited to promote their information

**Comment by christinerogers** [comment]
New News item - Please bump all existing cards to the right, moving 2019 IOP down to the second row

content, line by line: 
- [ ] card title: ICCN 2022 Geneva 
- [ ] image:  _@oldgandalf  please let derek know below in a comment what image to use _
- [ ] (Bold text/title below image:) **International Congress of Clinical Neurophysiology**
- [ ] Sept 4-8, 2022
- [ ]  Online Program  (hyperlinked to this URL:) https://ifcn.site-ym.com/mpage/ProgrammeOverview
- [ ] Two symposia organized by the GBC-OHBM-IFCN:
- [ ] (in bold)  **Quantitative Neuroimaging of Public Health problems: Examples from Latin America**
- [ ] Chair: Jorge Bosch-Bayard (Montreal Neurological Institute)
- [ ] (in bold) **EEG in the clouds**
- [ ] Chair: Pedro A. Valdes Sosa

@3design is this enough info to go on?  (what's missing?) if so - let us know below what URL we can look at it at, when ready to  review, thanks!  For monday would be perfect.

**Comment by 3design** [comment]
https://3design.github.io/GlobalBrainConsortium.org/news.html

**Comment by oldgandalf** [comment]
I find it perfect. Please, publish it

**Comment by christinerogers** [comment]
👍
