### ISSUE TITLE
Add INCF 2022 to the News page

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#79]
Hi Derek @3design 
Could you kindly add a card to the News page?  [news.html](https://globalbrainconsortium.org/news.html)
 All other cards should shift right (and then down)  

The styling within the card should roughly match the existing ICCN 2022 card in the same page

new card title: INCF Assembly 2022

image: use [this logo](https://neuroinformatics.incf.org/sites/default/files/neuroinformatics-logo-white.png) over a dark grey background (or whatever seems fitting)

(Bold text/title below image:) International Neuroinformatics Coordinating Facility (text hyperlinked to thisURL:) https://neuroinformatics.incf.org/2022/sessions
(new line, in bold:) Sept 12-16, 2022

Two symposia organized by the GBC: (please hyperlink this text to:) https://neuroinformatics.incf.org/2022/sessions

(in bold) GBC's EEG normative initiative for creating standards for MEEG analysis
(new line)Speakers: Pedro Valdes-Sosa, Joseph Picone, Christine Rogers, Scott Makeig

 (in bold) EEG: the interface between neuroinformatics and clinical/basic science research
(new line)Speakers: Pedro Valdes-Sosa, Michael Milham, Roberto Rodriguez, Tomas Ros, Jorge Bosch-Bayard

**Comment by 3design** [comment]
https://3design.github.io/GlobalBrainConsortium.org/news.html

**Comment by christinerogers** [comment]
thanks derek, it's good to go and thanks for merging and pushing to prod

**Comment by 3design** [comment]
Pushed to production

**Comment by christinerogers** [comment]
👍
