### ISSUE TITLE
Update GBC front page:  2023 meeting

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#80]
**placeholder** until meeting date is confirmed and materials (below) provided:
- [ ] Create carousel [image (based on 2021 image)](https://globalbrainconsortium.org/images/slider/2021meeting.jpg) to announce 2023 meeting 
- [ ] replace carousel image from 2021 meeting with this new one 
- [ ] replace section on main page for 2021 meeting with 2023 information

**Materials needed before assigning this issue to derek**: 
- [ ] new Events page panel to be copied  - see #80
or else: 
- [ ]  including a onedrive link for documents 
- [ ] specific title
- [ ] exact text (and any formatting instructions)
- [ ] new registration link

**Comment by christinerogers** [comment]
@oldgandalf can you give the **Materials need** section a go? 
* Is there a Registration link ? 
* Which 6 hours is the meeting scheduled for? 
* OneDrive link for documents?

**Comment by oldgandalf** [comment]
Hi Christine and Derek
I put the information for the News of the General Assembly on the GBC webpage.
It is in Teams, on the Global Brain Consortium /  GBCWebpage / Files / News / GBC Annual Assembly 2023
https://lstneuro.sharepoint.com/:f:/s/GlobalBrainConsortiumGBC/EsNWfNYXqLZDj0C1qnvqVyMBr98wfccIk25yogXWHfyeuA?e=JP4xsY

Derek, create new News on the webpage.

- I put a JPG image for the presentation: bannerGBCMarch2023.jpg
- The text for the News is in the file: Announcement.docx. A think you won't be able to upload the photos there.
- There should be a link to another subpage, where we will put more information about the meeting. For now, is under construction.

**Comment by 3design** [comment]
Hi @oldgandalf 

I had a look at the files you sent and there are some issues that we need to address before I can move on this item.

1. The images on the website for news items are 400px x 225px so the image supplied needs to be cropped to fit (and we will lose information)
2. The image has QR codes on it. If we reduce the image to the size stated above, the QR codes will no longer be usable
3. The written text doesn't follow the established layout. Could you please give me text written as follows:

Title of event: Annual meeting 2023 for example
What kind of event or subtitle: Virtual or in-person for example
Dates of event
Small summary and links (this is what you already provided)

Please let me know if you have any questions about the above

**Comment by christinerogers** [comment]
Derek (in case i miss it) - when you feel you have enough info from Bosch please tag this as next priority and keep us posted, thanks

**Comment by oldgandalf** [comment]
Hi @3design 
Use the file small_banner.png, to see how it works.
I modified the text in the announcement. Use it as it is. Maybe you will have just to delete the photos if it is plain text.

**Comment by 3design** [comment]
Hi @oldgandalf 
Thanks for the updates! I just opened announcement.doc and there is no text in the file!

**Comment by christinerogers** [comment]
HI, i just looked at https://3design.github.io/GlobalBrainConsortium.org/

before this is approved for production: 
- [ ] Please replace the carousel 2021 meeting card with the 2023 meeting announcement card

Please move "Virtual meeting" above the date so that it looks like the other events in this page. 

- [ ] Please delete: 
> Achievements of 2022. New projects in 2023. Inspirational presentations by outstanding researchers.
A Vera Gross Lecture by Dr. Michael P. Milham, Vice-president of the Child Mind Institute.
- [ ] and replace it with: 
Achievements of 2022. New projects in 2023. Inspirational presentations by outstanding researchers.
The Vera Gross public lecture will be presented by Dr. Michael P. Milham, Vice-president of the Child Mind Institute.

- [ ] add above the registration links - 
**To Register:** in bold

@oldgandalf, let me know how you feel about this - and question for you : 

re 2023 Annual Assembly of the GBC
- we did not have a 2022 assembly so "GBC General Assembly" is less confusing, no?

**Comment by christinerogers** [comment]
Hi @3design this looks perfect to me 👍   approved but --- 
can you tackle the #81 changes today? i'd prefer to push both to prod at once (once approved)

**Comment by christinerogers** [comment]
this was pushed to production Feb. 28
