### ISSUE TITLE
New page  for 2023 general meeting

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#81]
**placeholder** until date is confirmed and material below provided: 

- [ ] specific title for the item
- [ ] exact text (and any formatting instructions)
- [ ] new registration link 
- [ ] Onedrive link for documents? 
- [ ] Link to schedule / programme 
- [ ] instructions on what should happen to the cards that are displaced (display as orphans, or delete?)

note this content will be used for #80

**Comment by 3design** [comment]
Edits can be previewed here:

https://3design.github.io/GlobalBrainConsortium.org/event-annualMeeting-mar2023.html

**Comment by christinerogers** [comment]
this was pushed to production Feb. 28
