### ISSUE TITLE
update main page and Events, and 2023 meeting page - remove registration links

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#88]
Hi Derek, no rush but whenever you have a moment: 

- [x] index.html:  remove "To Register:" and the 2 registration links 

- [x] events.html:  remove "To Register:" and the 2 registration links 

- [x] event-annualMeeting-mar2023.html :  remove the 2 registration links 

thanks

**Comment by christinerogers** [comment]
@3design would you be able to make these quick fixes this week? thanks

**Comment by christinerogers** [comment]
Hi @3design this looks good but i see see the links online -- any idea why? 
e.g. https://globalbrainconsortium.org/
thanks for helping resolve this

**Comment by 3design** [comment]
@christinerogers The recent changes to the repo haven't been pushed to production yet. They can be viewed at https://3design.github.io/GlobalBrainConsortium.org/

**Comment by christinerogers** [comment]
perfect.  push it
