### ISSUE TITLE
add event: EEGNet flyer

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#90]
To the Events page, 

- [x] add a new card  EEGNet Virtual Colloquium
- [x] thumbnail: the flyer
- [x] Date line:  May 10, 2023 9h EDT

- [x] Text: 
Moderated by Alan Evans
Presentations by Pedro Valdes-Sosa, Jorge Bosch-Bayard, and Christine Rogers

 - [x] button: More information -> should open https://EEGNet.org in a new tab

**Comment by christinerogers** [comment]
hi @3design  - i didn't get to this before the colloquium, could you add this to the gbc site?  thanks

**Comment by 3design** [comment]
preview here 

https://3design.github.io/GlobalBrainConsortium.org/events.html
