### ISSUE TITLE
Add Covid (CIBD) project page

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#91]
while we wait for a few last details, (see below), let's get started  @3design 

- [x] update the Projects.html page to change `coming soon` button for Covid project to say `read more` and link to : 

- [x] a new `project-cibd.html` page (copied from project-malnutrition.html)

- [x] populate the sections ( Overview column, Goals column, Selected publications, and Participants) sections per this Word doc: 
[[https://lstneuro-my.sharepoint.com/:w:/g/personal/shahwar_yasir_neuroinformatics-collaboratory_org/Ea_7PPaSJ1pDh9XU0Bo9vHoBB3oObRztZTSb5krVTRMEJQ?rtime=U5CtDU1-20g]]

info coming soon: (email requests july 6)

- [ ] add images per section as indicated in the same word doc linked above 
 --- better quality images should come soon!  

- [ ] title for the page: COVID-Induced Brain Dysfunction
- [ ] banner image - if provided, if not use the GBC default banner image (booklet on red tablecloth)

**Comment by christinerogers** [comment]
@3design to make a rough first draft of this --

**Comment by 3design** [comment]
https://3design.github.io/GlobalBrainConsortium.org/project-cibd.html

**Comment by christinerogers** [comment]
Thanks derek!  beautiful stuff incorporating this morning's changes. 
 i think the last thing to do is push the change to Projects.html (`coming soon`-> `read more` with a link to the page) and we're done, no?
