### ISSUE TITLE
add EEGNet colloquium to Events page 

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#94]
placeholder, see christine/irem for details

**Comment by iremkatitas** [comment]
How about something like this based on the [launch announcement on GBC Website] @christinerogers (https://globalbrainconsortium.org/events.html)? 

- [Link to the poster image](https://drive.google.com/file/d/1iMeHBAttov4gbUuT-8EvhZ_pZJHOxg8s/view?usp=drive_link)

--- 

**_EEGNet Spring Colloquium 2024_**

![EEGNet_Spring_Colloquium_2024_flyer-GBC-events](https://github.com/3design/GlobalBrainConsortium.org/assets/56556663/7996b33d-d02d-4e65-bdc0-a4f82b31660d)


Virtual Meeting

May 23, 2024 11am EDT

Presentations by Alan Evans, Pedro Valdes-Sosa, Jorge Bosch-Bayard, Christine Rogers, Sid Segalowitz, Philippe Albouy, Sarah Lippé and Faisal Mushtaq

**Comment by christinerogers** [comment]
That's perfect, please just update this request to : 
- [ ] include a link to the flyer with speaker names instead. 
- [ ] include the Registration link for Eventbrite 

After that it will be good to ask Derek to take on .  merci!

**Comment by iremkatitas** [comment]
- [ ] the button should say register instead of read more - redirect to Eventbrite

**Comment by 3design** [comment]
I've provided the code snippet below so that we can edit what will be said 

`
        <div class="col-3 pad-left event">
          <h2 class="header-underline">EEGNet Spring Colloquium 2024</h2>
          <div class="card">
            <img src="images/thumbs/eegnet-thumb-2024.png">
            <h3>EEGNet Colloquium</h3>
            <p>Virtual Meeting</p>
            <p>May 23, 2024 11am EDT</p>
            <p>Presentations by Alan Evans, Pedro Valdes-Sosa, Jorge Bosch-Bayard, Christine Rogers, Sid Segalowitz, Philippe Albouy, Sarah Lippé and Faisal Mushtaq</p>
          </div>
          <a href="https://eegnet.org/"><button class="margin-center float-right">read more</button></a>
        </div>`

**Comment by christinerogers** [comment]
Thanks please put the speaker names in bullets

@iremkatitas please give Derek the Eventbrite link -- the button shouldn't link to EEGNet.org

**Comment by iremkatitas** [comment]
Hi @3design, thanks for the edit. The link for the button should be: [bit.ly/3TU6Dqk](bit.ly/3TU6Dqk)

**Comment by christinerogers** [comment]
good enough.  thanks very much @3design
