### ISSUE TITLE
GBC Website update

### ISSUE THREAD

**Issue by 3design** [3design/GlobalBrainConsortium.org#95]
- For the 2024 Colloquium event - Change the register button to "view on Youtube" and link it to the [colloquium video](https://youtu.be/PpC20ch8uPw?si=7C_yp_7Z8vRQp3rM)

- Add a new event posting

Name: Global Open Science Electrophysiology Educational Course at OHBM"
Location: Seoul, Korea
Date: June 23, 2024 9am- 5:30pm KST
Description: Speakers: Pedro Valdes-Sosa, Maria Bringas-Vega, Alan Evans, Qing Wang
Button to say "read more" and link to https://ww6.aievolution.com/hbm2401/index.cfm?do=ev.viewEv&ev=1566

**Comment by christinerogers** [comment]
Thanks @3design  - please merge and push this to production asap. 

cc @iremkatitas to check that it reads ok and makes reasonable sense.

**Comment by 3design** [comment]
Pushed and live

**Comment by iremkatitas** [comment]
Looks good, thank you @3design
