### ISSUE TITLE
[About] fix broken steering image - Paul thompson screenshot

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#98]
His headshot is now broken - should be a quick fix for Monday. 

Thanks @3design when you're back at your post (not urgent before then, i'm just queuing up tickets)

**Comment by 3design** [comment]
![FireShot Capture 086 - Global Brain Consortium About Us - globalbrainconsortium org](https://github.com/user-attachments/assets/6c29ca8c-ee13-4c5b-8a6a-f1e1daac6510)

@christinerogers I have looked at the production website on a few different browsers and the image seems to be okay. Can you please verify that it is broken? Could you be viewing a cached version of the website?

**Comment by christinerogers** [comment]
Thanks Derek, glad it's a non issue.  Yes probably cached
