### ISSUE TITLE
Chengdu meeting --add to the GBC website 

### ISSUE THREAD

**Issue by christinerogers** [3design/GlobalBrainConsortium.org#99]
Please take the first steps Monday (or when you're back at work) and then flag me for review @3design  --

To announce the GBC meeting happening in September in Chengdu : 
Please re-purpose the 2023 GBC meeting materials we had on the website 

Important: 
* The meeting details are all here:    [http://neurotech-2024.com/index.html](http://neurotech-2024.com/index.html)
* Note this meeting is _in person not on zoom_. 

To do -- Just like for the 2023 meeting, the meeting info should be visible in a few places on the GBC site: 

- [x] Carousel graphic on the home page  (this will need a graphic, try to update 2023 GBC meeting carousel image) 
- [x] panel on the home page - replace current OHBM 2024 panel on the home page
- [x] Events page : create a new event, try to copy/adapt the 2023 GBC meeting announcement

**Comment by 3design** [comment]
@christinerogers I've added the information for the Chengdu event to the website and it can be previewed here:

https://3design.github.io/GlobalBrainConsortium.org/index.html
https://3design.github.io/GlobalBrainConsortium.org/events.html
https://3design.github.io/GlobalBrainConsortium.org/event-annualMeeting-sept2024.html

I'm not too sure if you want the full list of speakers on the meeting page as it is on the schedule linked on the meeting page. As always, let me know if you'd like any changes to what I've put together.

**Comment by christinerogers** [comment]
thanks @3design  for the jumpstart, given there's no PR I"ll add comments here. 
Could you please, asap: 

in the carousel: 
- [ ] change SEPTEMBER 6 TO 8 to September 6-8, 2024
- [ ] remove the 2023 meeting graphic / image 

In the page about the meeting -- in the left column: 
- [ ] change (remove) the meeting chairs section with Pedro and Alan and their photos
- [ ] replace "Meeting Chairs" title with "Meeting Links"  and below it include 2 blue buttons that say for  "Meeting Website" and then under it : "Register now"  
- [ ] remove the words "Meeting Program" and the link Icon just above it.  

In the right column of the meeting webpage: 
- [ ] remove the "Register now" link and the "Go to Website" button at bottom"
- [ ] Bold the first 2 lines "Chengdu ... 2024"

**Comment by christinerogers** [comment]
beautiful.  it all looks good, including the Events page.  

I'll merge this - - Could you please: ask John/Andy to push to production asap, and then get back to me both with the best-guess timeline, and then when it's online 
Un grand merci

**Comment by 3design** [comment]
@christinerogers It's on production now :)
